# Defining

direction: down

A: {
  label: "Defining product vision"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

B: {
  label: "Define value proposition"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

C: {
  label: "Define Success criteria"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

D: {
  label: "Product research"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

E: {
  label: "Conduct user research"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

F: {
  label: "User analysis"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

G: {
  label: "User analysis"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

H: {
  label: "Ideation"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

I: {
  label: "Plan structure of product"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

J: {
  label: "Generate Ideas"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

K: {
  label: "Validate Ideas"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

L: {
  label: "Design"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

M: {
  label: "Design Handoff"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

N: {
  label: "Testing and Validation"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

A -> B
B -> C
C -> D
D -> E
E -> F
E -> F
E -> F
E -> G
G -> H
H -> I
I -> J
J -> K
J -> K
J -> K
J -> K
K -> L
L -> M
M -> N
