# Earth

direction: down

A: {
  label: "Is Jupiter Gas?"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

B: {
  label: "Planet is Gas"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

C: {
  label: "Gravity on Jupiter"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

D: {
  label: "Gravity on Earth"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

E: {
  label: "Air held on Earth"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

F: {
  label: "No Air on Earth"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

A -> B
A -> C
C -> B
C -> D
D -> E
D -> F
