# Manager

direction: down

A: {
  label: "Manager L&D"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

B: {
  label: "Reliance Jio"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

C: {
  label: "Cognizant"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

D: {
  label: "HDFC Life"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

E: {
  label: "MAX Fashions"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

F: {
  label: "Freelance Trainer"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

G: {
  label: "G"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

A -> B
A -> C
A -> D
A -> E
A -> F
B -> G
C -> G
D -> G
E -> G
F -> G
