# Simple

direction: down

AB: {
  label: "Source AB"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

A: {
  label: "Target A"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

B: {
  label: "Target B"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

BC: {
  label: "Source BC"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

C: {
  label: "Target C"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

AB -> A
AB -> B
BC -> B
BC -> C
