# Thank

direction: down

A: {
  label: "Thank you"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

B: {
  label: "Part of journey"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

C: {
  label: "Project not come far"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

D: {
  label: "Valuable support"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

E: {
  label: "Enterprise Sales"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

F: {
  label: "HR"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

G: {
  label: "Enterprise Academy"
  shape: rectangle
  style: {
    fill: "#87CEEB"
    stroke: "#4682B4"
    stroke-width: 1
  }
}

A -> B
B -> C
C -> D
D -> E
D -> F
D -> G
